development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://nvvgmgnorflkls:4fecfbef17cbd7b97ab03ad7d5bb69ce8a18fea10041d79c0823f3bd3f53bb77@ec2-50-16-185-9.compute-1.amazonaws.com:5432/d324ei2e0lkt2k
  channel_prefix: app_production
